/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import ynab.client.model.Account;
import ynab.client.model.BudgetSummary;
import ynab.client.model.Category;
import ynab.client.model.CategoryGroup;
import ynab.client.model.CurrencyFormat;
import ynab.client.model.DateFormat;
import ynab.client.model.MonthDetail;
import ynab.client.model.Payee;
import ynab.client.model.PayeeLocation;
import ynab.client.model.ScheduledSubTransaction;
import ynab.client.model.ScheduledTransactionSummary;
import ynab.client.model.SubTransaction;
import ynab.client.model.TransactionSummary;

/**
 * BudgetDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-25T01:42:20.552-05:00")
public class BudgetDetail {
  @SerializedName("id")
  private UUID id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("date_format")
  private DateFormat dateFormat = null;

  @SerializedName("currency_format")
  private CurrencyFormat currencyFormat = null;

  @SerializedName("accounts")
  private List<Account> accounts = null;

  @SerializedName("payees")
  private List<Payee> payees = null;

  @SerializedName("payee_locations")
  private List<PayeeLocation> payeeLocations = null;

  @SerializedName("category_groups")
  private List<CategoryGroup> categoryGroups = null;

  @SerializedName("categories")
  private List<Category> categories = null;

  @SerializedName("months")
  private List<MonthDetail> months = null;

  @SerializedName("transactions")
  private List<TransactionSummary> transactions = null;

  @SerializedName("subtransactions")
  private List<SubTransaction> subtransactions = null;

  @SerializedName("scheduled_transactions")
  private List<ScheduledTransactionSummary> scheduledTransactions = null;

  @SerializedName("scheduled_subtransactions")
  private List<ScheduledSubTransaction> scheduledSubtransactions = null;

  public BudgetDetail id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public BudgetDetail name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BudgetDetail dateFormat(DateFormat dateFormat) {
    this.dateFormat = dateFormat;
    return this;
  }

   /**
   * Get dateFormat
   * @return dateFormat
  **/
  @ApiModelProperty(value = "")
  public DateFormat getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(DateFormat dateFormat) {
    this.dateFormat = dateFormat;
  }

  public BudgetDetail currencyFormat(CurrencyFormat currencyFormat) {
    this.currencyFormat = currencyFormat;
    return this;
  }

   /**
   * Get currencyFormat
   * @return currencyFormat
  **/
  @ApiModelProperty(value = "")
  public CurrencyFormat getCurrencyFormat() {
    return currencyFormat;
  }

  public void setCurrencyFormat(CurrencyFormat currencyFormat) {
    this.currencyFormat = currencyFormat;
  }

  public BudgetDetail accounts(List<Account> accounts) {
    this.accounts = accounts;
    return this;
  }

  public BudgetDetail addAccountsItem(Account accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<Account>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

   /**
   * Get accounts
   * @return accounts
  **/
  @ApiModelProperty(value = "")
  public List<Account> getAccounts() {
    return accounts;
  }

  public void setAccounts(List<Account> accounts) {
    this.accounts = accounts;
  }

  public BudgetDetail payees(List<Payee> payees) {
    this.payees = payees;
    return this;
  }

  public BudgetDetail addPayeesItem(Payee payeesItem) {
    if (this.payees == null) {
      this.payees = new ArrayList<Payee>();
    }
    this.payees.add(payeesItem);
    return this;
  }

   /**
   * Get payees
   * @return payees
  **/
  @ApiModelProperty(value = "")
  public List<Payee> getPayees() {
    return payees;
  }

  public void setPayees(List<Payee> payees) {
    this.payees = payees;
  }

  public BudgetDetail payeeLocations(List<PayeeLocation> payeeLocations) {
    this.payeeLocations = payeeLocations;
    return this;
  }

  public BudgetDetail addPayeeLocationsItem(PayeeLocation payeeLocationsItem) {
    if (this.payeeLocations == null) {
      this.payeeLocations = new ArrayList<PayeeLocation>();
    }
    this.payeeLocations.add(payeeLocationsItem);
    return this;
  }

   /**
   * Get payeeLocations
   * @return payeeLocations
  **/
  @ApiModelProperty(value = "")
  public List<PayeeLocation> getPayeeLocations() {
    return payeeLocations;
  }

  public void setPayeeLocations(List<PayeeLocation> payeeLocations) {
    this.payeeLocations = payeeLocations;
  }

  public BudgetDetail categoryGroups(List<CategoryGroup> categoryGroups) {
    this.categoryGroups = categoryGroups;
    return this;
  }

  public BudgetDetail addCategoryGroupsItem(CategoryGroup categoryGroupsItem) {
    if (this.categoryGroups == null) {
      this.categoryGroups = new ArrayList<CategoryGroup>();
    }
    this.categoryGroups.add(categoryGroupsItem);
    return this;
  }

   /**
   * Get categoryGroups
   * @return categoryGroups
  **/
  @ApiModelProperty(value = "")
  public List<CategoryGroup> getCategoryGroups() {
    return categoryGroups;
  }

  public void setCategoryGroups(List<CategoryGroup> categoryGroups) {
    this.categoryGroups = categoryGroups;
  }

  public BudgetDetail categories(List<Category> categories) {
    this.categories = categories;
    return this;
  }

  public BudgetDetail addCategoriesItem(Category categoriesItem) {
    if (this.categories == null) {
      this.categories = new ArrayList<Category>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Get categories
   * @return categories
  **/
  @ApiModelProperty(value = "")
  public List<Category> getCategories() {
    return categories;
  }

  public void setCategories(List<Category> categories) {
    this.categories = categories;
  }

  public BudgetDetail months(List<MonthDetail> months) {
    this.months = months;
    return this;
  }

  public BudgetDetail addMonthsItem(MonthDetail monthsItem) {
    if (this.months == null) {
      this.months = new ArrayList<MonthDetail>();
    }
    this.months.add(monthsItem);
    return this;
  }

   /**
   * Get months
   * @return months
  **/
  @ApiModelProperty(value = "")
  public List<MonthDetail> getMonths() {
    return months;
  }

  public void setMonths(List<MonthDetail> months) {
    this.months = months;
  }

  public BudgetDetail transactions(List<TransactionSummary> transactions) {
    this.transactions = transactions;
    return this;
  }

  public BudgetDetail addTransactionsItem(TransactionSummary transactionsItem) {
    if (this.transactions == null) {
      this.transactions = new ArrayList<TransactionSummary>();
    }
    this.transactions.add(transactionsItem);
    return this;
  }

   /**
   * Get transactions
   * @return transactions
  **/
  @ApiModelProperty(value = "")
  public List<TransactionSummary> getTransactions() {
    return transactions;
  }

  public void setTransactions(List<TransactionSummary> transactions) {
    this.transactions = transactions;
  }

  public BudgetDetail subtransactions(List<SubTransaction> subtransactions) {
    this.subtransactions = subtransactions;
    return this;
  }

  public BudgetDetail addSubtransactionsItem(SubTransaction subtransactionsItem) {
    if (this.subtransactions == null) {
      this.subtransactions = new ArrayList<SubTransaction>();
    }
    this.subtransactions.add(subtransactionsItem);
    return this;
  }

   /**
   * Get subtransactions
   * @return subtransactions
  **/
  @ApiModelProperty(value = "")
  public List<SubTransaction> getSubtransactions() {
    return subtransactions;
  }

  public void setSubtransactions(List<SubTransaction> subtransactions) {
    this.subtransactions = subtransactions;
  }

  public BudgetDetail scheduledTransactions(List<ScheduledTransactionSummary> scheduledTransactions) {
    this.scheduledTransactions = scheduledTransactions;
    return this;
  }

  public BudgetDetail addScheduledTransactionsItem(ScheduledTransactionSummary scheduledTransactionsItem) {
    if (this.scheduledTransactions == null) {
      this.scheduledTransactions = new ArrayList<ScheduledTransactionSummary>();
    }
    this.scheduledTransactions.add(scheduledTransactionsItem);
    return this;
  }

   /**
   * Get scheduledTransactions
   * @return scheduledTransactions
  **/
  @ApiModelProperty(value = "")
  public List<ScheduledTransactionSummary> getScheduledTransactions() {
    return scheduledTransactions;
  }

  public void setScheduledTransactions(List<ScheduledTransactionSummary> scheduledTransactions) {
    this.scheduledTransactions = scheduledTransactions;
  }

  public BudgetDetail scheduledSubtransactions(List<ScheduledSubTransaction> scheduledSubtransactions) {
    this.scheduledSubtransactions = scheduledSubtransactions;
    return this;
  }

  public BudgetDetail addScheduledSubtransactionsItem(ScheduledSubTransaction scheduledSubtransactionsItem) {
    if (this.scheduledSubtransactions == null) {
      this.scheduledSubtransactions = new ArrayList<ScheduledSubTransaction>();
    }
    this.scheduledSubtransactions.add(scheduledSubtransactionsItem);
    return this;
  }

   /**
   * Get scheduledSubtransactions
   * @return scheduledSubtransactions
  **/
  @ApiModelProperty(value = "")
  public List<ScheduledSubTransaction> getScheduledSubtransactions() {
    return scheduledSubtransactions;
  }

  public void setScheduledSubtransactions(List<ScheduledSubTransaction> scheduledSubtransactions) {
    this.scheduledSubtransactions = scheduledSubtransactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BudgetDetail budgetDetail = (BudgetDetail) o;
    return Objects.equals(this.id, budgetDetail.id) &&
        Objects.equals(this.name, budgetDetail.name) &&
        Objects.equals(this.dateFormat, budgetDetail.dateFormat) &&
        Objects.equals(this.currencyFormat, budgetDetail.currencyFormat) &&
        Objects.equals(this.accounts, budgetDetail.accounts) &&
        Objects.equals(this.payees, budgetDetail.payees) &&
        Objects.equals(this.payeeLocations, budgetDetail.payeeLocations) &&
        Objects.equals(this.categoryGroups, budgetDetail.categoryGroups) &&
        Objects.equals(this.categories, budgetDetail.categories) &&
        Objects.equals(this.months, budgetDetail.months) &&
        Objects.equals(this.transactions, budgetDetail.transactions) &&
        Objects.equals(this.subtransactions, budgetDetail.subtransactions) &&
        Objects.equals(this.scheduledTransactions, budgetDetail.scheduledTransactions) &&
        Objects.equals(this.scheduledSubtransactions, budgetDetail.scheduledSubtransactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, dateFormat, currencyFormat, accounts, payees, payeeLocations, categoryGroups, categories, months, transactions, subtransactions, scheduledTransactions, scheduledSubtransactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BudgetDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    currencyFormat: ").append(toIndentedString(currencyFormat)).append("\n");
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("    payees: ").append(toIndentedString(payees)).append("\n");
    sb.append("    payeeLocations: ").append(toIndentedString(payeeLocations)).append("\n");
    sb.append("    categoryGroups: ").append(toIndentedString(categoryGroups)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    months: ").append(toIndentedString(months)).append("\n");
    sb.append("    transactions: ").append(toIndentedString(transactions)).append("\n");
    sb.append("    subtransactions: ").append(toIndentedString(subtransactions)).append("\n");
    sb.append("    scheduledTransactions: ").append(toIndentedString(scheduledTransactions)).append("\n");
    sb.append("    scheduledSubtransactions: ").append(toIndentedString(scheduledSubtransactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

