/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import ynab.client.model.BudgetDetail;

/**
 * BudgetDetailWrapper
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-25T01:42:20.552-05:00")
public class BudgetDetailWrapper {
  @SerializedName("budget")
  private BudgetDetail budget = null;

  @SerializedName("server_knowledge")
  private BigDecimal serverKnowledge = null;

  public BudgetDetailWrapper budget(BudgetDetail budget) {
    this.budget = budget;
    return this;
  }

   /**
   * Get budget
   * @return budget
  **/
  @ApiModelProperty(required = true, value = "")
  public BudgetDetail getBudget() {
    return budget;
  }

  public void setBudget(BudgetDetail budget) {
    this.budget = budget;
  }

  public BudgetDetailWrapper serverKnowledge(BigDecimal serverKnowledge) {
    this.serverKnowledge = serverKnowledge;
    return this;
  }

   /**
   * The knowledge of the server
   * @return serverKnowledge
  **/
  @ApiModelProperty(required = true, value = "The knowledge of the server")
  public BigDecimal getServerKnowledge() {
    return serverKnowledge;
  }

  public void setServerKnowledge(BigDecimal serverKnowledge) {
    this.serverKnowledge = serverKnowledge;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BudgetDetailWrapper budgetDetailWrapper = (BudgetDetailWrapper) o;
    return Objects.equals(this.budget, budgetDetailWrapper.budget) &&
        Objects.equals(this.serverKnowledge, budgetDetailWrapper.serverKnowledge);
  }

  @Override
  public int hashCode() {
    return Objects.hash(budget, serverKnowledge);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BudgetDetailWrapper {\n");
    
    sb.append("    budget: ").append(toIndentedString(budget)).append("\n");
    sb.append("    serverKnowledge: ").append(toIndentedString(serverKnowledge)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

