/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BulkIds
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-25T01:42:20.552-05:00")
public class BulkIds {
  @SerializedName("transaction_ids")
  private List<String> transactionIds = new ArrayList<String>();

  @SerializedName("duplicate_import_ids")
  private List<String> duplicateImportIds = new ArrayList<String>();

  public BulkIds transactionIds(List<String> transactionIds) {
    this.transactionIds = transactionIds;
    return this;
  }

  public BulkIds addTransactionIdsItem(String transactionIdsItem) {
    this.transactionIds.add(transactionIdsItem);
    return this;
  }

   /**
   * The list of Transaction IDs that were created.
   * @return transactionIds
  **/
  @ApiModelProperty(required = true, value = "The list of Transaction IDs that were created.")
  public List<String> getTransactionIds() {
    return transactionIds;
  }

  public void setTransactionIds(List<String> transactionIds) {
    this.transactionIds = transactionIds;
  }

  public BulkIds duplicateImportIds(List<String> duplicateImportIds) {
    this.duplicateImportIds = duplicateImportIds;
    return this;
  }

  public BulkIds addDuplicateImportIdsItem(String duplicateImportIdsItem) {
    this.duplicateImportIds.add(duplicateImportIdsItem);
    return this;
  }

   /**
   * If any Transactions were not created because they had an import_id matching a transaction already on the same account, the specified import_id(s) will be included in this list.
   * @return duplicateImportIds
  **/
  @ApiModelProperty(required = true, value = "If any Transactions were not created because they had an import_id matching a transaction already on the same account, the specified import_id(s) will be included in this list.")
  public List<String> getDuplicateImportIds() {
    return duplicateImportIds;
  }

  public void setDuplicateImportIds(List<String> duplicateImportIds) {
    this.duplicateImportIds = duplicateImportIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkIds bulkIds = (BulkIds) o;
    return Objects.equals(this.transactionIds, bulkIds.transactionIds) &&
        Objects.equals(this.duplicateImportIds, bulkIds.duplicateImportIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionIds, duplicateImportIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkIds {\n");
    
    sb.append("    transactionIds: ").append(toIndentedString(transactionIds)).append("\n");
    sb.append("    duplicateImportIds: ").append(toIndentedString(duplicateImportIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

