/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Category
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-25T01:42:20.552-05:00")
public class Category {
  @SerializedName("id")
  private String id = null;

  @SerializedName("category_group_id")
  private String categoryGroupId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("hidden")
  private Boolean hidden = null;

  @SerializedName("budgeted")
  private BigDecimal budgeted = null;

  @SerializedName("activity")
  private BigDecimal activity = null;

  @SerializedName("balance")
  private BigDecimal balance = null;

  @SerializedName("deleted")
  private Boolean deleted = null;

  public Category id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Category categoryGroupId(String categoryGroupId) {
    this.categoryGroupId = categoryGroupId;
    return this;
  }

   /**
   * Get categoryGroupId
   * @return categoryGroupId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCategoryGroupId() {
    return categoryGroupId;
  }

  public void setCategoryGroupId(String categoryGroupId) {
    this.categoryGroupId = categoryGroupId;
  }

  public Category name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Category hidden(Boolean hidden) {
    this.hidden = hidden;
    return this;
  }

   /**
   * Whether or not the category is hidden
   * @return hidden
  **/
  @ApiModelProperty(required = true, value = "Whether or not the category is hidden")
  public Boolean isHidden() {
    return hidden;
  }

  public void setHidden(Boolean hidden) {
    this.hidden = hidden;
  }

  public Category budgeted(BigDecimal budgeted) {
    this.budgeted = budgeted;
    return this;
  }

   /**
   * Budgeted amount in current month in milliunits format
   * @return budgeted
  **/
  @ApiModelProperty(required = true, value = "Budgeted amount in current month in milliunits format")
  public BigDecimal getBudgeted() {
    return budgeted;
  }

  public void setBudgeted(BigDecimal budgeted) {
    this.budgeted = budgeted;
  }

  public Category activity(BigDecimal activity) {
    this.activity = activity;
    return this;
  }

   /**
   * Activity amount in current month in milliunits format
   * @return activity
  **/
  @ApiModelProperty(required = true, value = "Activity amount in current month in milliunits format")
  public BigDecimal getActivity() {
    return activity;
  }

  public void setActivity(BigDecimal activity) {
    this.activity = activity;
  }

  public Category balance(BigDecimal balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Balance in current month in milliunits format
   * @return balance
  **/
  @ApiModelProperty(required = true, value = "Balance in current month in milliunits format")
  public BigDecimal getBalance() {
    return balance;
  }

  public void setBalance(BigDecimal balance) {
    this.balance = balance;
  }

  public Category deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Whether or not the category has been deleted.  Deleted categories will only be included in delta requests.
   * @return deleted
  **/
  @ApiModelProperty(required = true, value = "Whether or not the category has been deleted.  Deleted categories will only be included in delta requests.")
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Category category = (Category) o;
    return Objects.equals(this.id, category.id) &&
        Objects.equals(this.categoryGroupId, category.categoryGroupId) &&
        Objects.equals(this.name, category.name) &&
        Objects.equals(this.hidden, category.hidden) &&
        Objects.equals(this.budgeted, category.budgeted) &&
        Objects.equals(this.activity, category.activity) &&
        Objects.equals(this.balance, category.balance) &&
        Objects.equals(this.deleted, category.deleted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, categoryGroupId, name, hidden, budgeted, activity, balance, deleted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Category {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    categoryGroupId: ").append(toIndentedString(categoryGroupId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    hidden: ").append(toIndentedString(hidden)).append("\n");
    sb.append("    budgeted: ").append(toIndentedString(budgeted)).append("\n");
    sb.append("    activity: ").append(toIndentedString(activity)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

