/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import ynab.client.model.MonthSummary;

/**
 * MonthSummariesWrapper
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-25T01:42:20.552-05:00")
public class MonthSummariesWrapper {
  @SerializedName("months")
  private List<MonthSummary> months = new ArrayList<MonthSummary>();

  public MonthSummariesWrapper months(List<MonthSummary> months) {
    this.months = months;
    return this;
  }

  public MonthSummariesWrapper addMonthsItem(MonthSummary monthsItem) {
    this.months.add(monthsItem);
    return this;
  }

   /**
   * Get months
   * @return months
  **/
  @ApiModelProperty(required = true, value = "")
  public List<MonthSummary> getMonths() {
    return months;
  }

  public void setMonths(List<MonthSummary> months) {
    this.months = months;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonthSummariesWrapper monthSummariesWrapper = (MonthSummariesWrapper) o;
    return Objects.equals(this.months, monthSummariesWrapper.months);
  }

  @Override
  public int hashCode() {
    return Objects.hash(months);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonthSummariesWrapper {\n");
    
    sb.append("    months: ").append(toIndentedString(months)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

