/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import ynab.client.model.PayeeLocation;

/**
 * PayeeLocationsWrapper
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-25T01:42:20.552-05:00")
public class PayeeLocationsWrapper {
  @SerializedName("payee_locations")
  private List<PayeeLocation> payeeLocations = new ArrayList<PayeeLocation>();

  public PayeeLocationsWrapper payeeLocations(List<PayeeLocation> payeeLocations) {
    this.payeeLocations = payeeLocations;
    return this;
  }

  public PayeeLocationsWrapper addPayeeLocationsItem(PayeeLocation payeeLocationsItem) {
    this.payeeLocations.add(payeeLocationsItem);
    return this;
  }

   /**
   * Get payeeLocations
   * @return payeeLocations
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PayeeLocation> getPayeeLocations() {
    return payeeLocations;
  }

  public void setPayeeLocations(List<PayeeLocation> payeeLocations) {
    this.payeeLocations = payeeLocations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayeeLocationsWrapper payeeLocationsWrapper = (PayeeLocationsWrapper) o;
    return Objects.equals(this.payeeLocations, payeeLocationsWrapper.payeeLocations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(payeeLocations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayeeLocationsWrapper {\n");
    
    sb.append("    payeeLocations: ").append(toIndentedString(payeeLocations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

