/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.List;
import org.threeten.bp.LocalDate;
import ynab.client.model.ScheduledSubTransaction;
import ynab.client.model.ScheduledTransactionSummary;

/**
 * ScheduledTransactionDetail
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-25T01:42:20.552-05:00")
public class ScheduledTransactionDetail {
  @SerializedName("id")
  private String id = null;

  @SerializedName("date_first")
  private LocalDate dateFirst = null;

  @SerializedName("date_next")
  private LocalDate dateNext = null;

  /**
   * Gets or Sets frequency
   */
  @JsonAdapter(FrequencyEnum.Adapter.class)
  public enum FrequencyEnum {
    NEVER("never"),
    
    DAILY("daily"),
    
    WEEKLY("weekly"),
    
    EVERYOTHERWEEK("everyOtherWeek"),
    
    TWICEAMONTH("twiceAMonth"),
    
    EVERY4WEEKS("every4Weeks"),
    
    MONTHLY("monthly"),
    
    EVERYOTHERMONTH("everyOtherMonth"),
    
    EVERY3MONTHS("every3Months"),
    
    EVERY4MONTHS("every4Months"),
    
    TWICEAYEAR("twiceAYear"),
    
    YEARLY("yearly"),
    
    EVERYOTHERYEAR("everyOtherYear");

    private String value;

    FrequencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FrequencyEnum fromValue(String text) {
      for (FrequencyEnum b : FrequencyEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<FrequencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FrequencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FrequencyEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return FrequencyEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("frequency")
  private FrequencyEnum frequency = null;

  @SerializedName("amount")
  private BigDecimal amount = null;

  @SerializedName("account_id")
  private String accountId = null;

  @SerializedName("deleted")
  private Boolean deleted = null;

  @SerializedName("account_name")
  private String accountName = null;

  @SerializedName("subtransactions")
  private List<ScheduledSubTransaction> subtransactions = new ArrayList<ScheduledSubTransaction>();

  public ScheduledTransactionDetail id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ScheduledTransactionDetail dateFirst(LocalDate dateFirst) {
    this.dateFirst = dateFirst;
    return this;
  }

   /**
   * The first date for which the Scheduled Transaction was scheduled.
   * @return dateFirst
  **/
  @ApiModelProperty(required = true, value = "The first date for which the Scheduled Transaction was scheduled.")
  public LocalDate getDateFirst() {
    return dateFirst;
  }

  public void setDateFirst(LocalDate dateFirst) {
    this.dateFirst = dateFirst;
  }

  public ScheduledTransactionDetail dateNext(LocalDate dateNext) {
    this.dateNext = dateNext;
    return this;
  }

   /**
   * The next date for which the Scheduled Transaction is scheduled.
   * @return dateNext
  **/
  @ApiModelProperty(required = true, value = "The next date for which the Scheduled Transaction is scheduled.")
  public LocalDate getDateNext() {
    return dateNext;
  }

  public void setDateNext(LocalDate dateNext) {
    this.dateNext = dateNext;
  }

  public ScheduledTransactionDetail frequency(FrequencyEnum frequency) {
    this.frequency = frequency;
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  @ApiModelProperty(required = true, value = "")
  public FrequencyEnum getFrequency() {
    return frequency;
  }

  public void setFrequency(FrequencyEnum frequency) {
    this.frequency = frequency;
  }

  public ScheduledTransactionDetail amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The scheduled transaction amount in milliunits format
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "The scheduled transaction amount in milliunits format")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public ScheduledTransactionDetail accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public ScheduledTransactionDetail deleted(Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

   /**
   * Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.
   * @return deleted
  **/
  @ApiModelProperty(required = true, value = "Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.")
  public Boolean isDeleted() {
    return deleted;
  }

  public void setDeleted(Boolean deleted) {
    this.deleted = deleted;
  }

  public ScheduledTransactionDetail accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public ScheduledTransactionDetail subtransactions(List<ScheduledSubTransaction> subtransactions) {
    this.subtransactions = subtransactions;
    return this;
  }

  public ScheduledTransactionDetail addSubtransactionsItem(ScheduledSubTransaction subtransactionsItem) {
    this.subtransactions.add(subtransactionsItem);
    return this;
  }

   /**
   * If a split scheduled transaction, the subtransactions.
   * @return subtransactions
  **/
  @ApiModelProperty(required = true, value = "If a split scheduled transaction, the subtransactions.")
  public List<ScheduledSubTransaction> getSubtransactions() {
    return subtransactions;
  }

  public void setSubtransactions(List<ScheduledSubTransaction> subtransactions) {
    this.subtransactions = subtransactions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduledTransactionDetail scheduledTransactionDetail = (ScheduledTransactionDetail) o;
    return Objects.equals(this.id, scheduledTransactionDetail.id) &&
        Objects.equals(this.dateFirst, scheduledTransactionDetail.dateFirst) &&
        Objects.equals(this.dateNext, scheduledTransactionDetail.dateNext) &&
        Objects.equals(this.frequency, scheduledTransactionDetail.frequency) &&
        Objects.equals(this.amount, scheduledTransactionDetail.amount) &&
        Objects.equals(this.accountId, scheduledTransactionDetail.accountId) &&
        Objects.equals(this.deleted, scheduledTransactionDetail.deleted) &&
        Objects.equals(this.accountName, scheduledTransactionDetail.accountName) &&
        Objects.equals(this.subtransactions, scheduledTransactionDetail.subtransactions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, dateFirst, dateNext, frequency, amount, accountId, deleted, accountName, subtransactions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduledTransactionDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    dateFirst: ").append(toIndentedString(dateFirst)).append("\n");
    sb.append("    dateNext: ").append(toIndentedString(dateNext)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    subtransactions: ").append(toIndentedString(subtransactions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

