/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.api;

import ynab.client.invoker.ApiException;
import ynab.client.model.AccountResponse;
import ynab.client.model.AccountsResponse;
import ynab.client.model.ErrorResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountsApi
 */
@Ignore
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    
    /**
     * Single account
     *
     * Returns a single account
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountByIdTest() throws ApiException {
        UUID budgetId = null;
        UUID accountId = null;
        AccountResponse response = api.getAccountById(budgetId, accountId);

        // TODO: test validations
    }
    
    /**
     * Account list
     *
     * Returns all accounts
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountsTest() throws ApiException {
        UUID budgetId = null;
        AccountsResponse response = api.getAccounts(budgetId);

        // TODO: test validations
    }
    
}
