/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.api;

import ynab.client.invoker.ApiException;
import java.math.BigDecimal;
import ynab.client.model.BudgetDetailResponse;
import ynab.client.model.BudgetSummaryResponse;
import ynab.client.model.ErrorResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BudgetsApi
 */
@Ignore
public class BudgetsApiTest {

    private final BudgetsApi api = new BudgetsApi();

    
    /**
     * Single budget
     *
     * Returns a single budget with all related entities.  This resource is effectively a full budget export.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBudgetByIdTest() throws ApiException {
        UUID budgetId = null;
        BigDecimal lastKnowledgeOfServer = null;
        BudgetDetailResponse response = api.getBudgetById(budgetId, lastKnowledgeOfServer);

        // TODO: test validations
    }
    
    /**
     * List budgets
     *
     * Returns budgets list with summary information.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBudgetsTest() throws ApiException {
        BudgetSummaryResponse response = api.getBudgets();

        // TODO: test validations
    }
    
}
