/*
 * YNAB API Endpoints
 * Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.youneedabudget.com
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ynab.client.api;

import ynab.client.invoker.ApiException;
import ynab.client.model.CategoriesResponse;
import ynab.client.model.CategoryResponse;
import ynab.client.model.ErrorResponse;
import java.util.List;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CategoriesApi
 */
@Ignore
public class CategoriesApiTest {

    private final CategoriesApi api = new CategoriesApi();

    
    /**
     * List categories
     *
     * Returns all categories grouped by category group.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCategoriesTest() throws ApiException {
        String budgetId = null;
        CategoriesResponse response = api.getCategories(budgetId);

        // TODO: test validations
    }
    
    /**
     * Single category
     *
     * Returns a single category
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCategoryByIdTest() throws ApiException {
        String budgetId = null;
        String categoryId = null;
        CategoryResponse response = api.getCategoryById(budgetId, categoryId);

        // TODO: test validations
    }
    
}
